<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>DataDriven_CreateCustomer</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>991a119a-3049-4d0a-894f-5db48953f901</testSuiteGuid>
   <testCaseLink>
      <guid>060fde91-244a-4e92-8e73-4cc4f8bae046</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_010_PostRequest_DynamicData_Customer</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>1bfd46bb-abcd-44bd-bc46-7eed0f2e8b36</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/DataDriven_CreateCustomer</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>1bfd46bb-abcd-44bd-bc46-7eed0f2e8b36</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>First_Input</value>
         <variableId>adf5f686-f696-40d7-a113-e9ef5cff5806</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>1bfd46bb-abcd-44bd-bc46-7eed0f2e8b36</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Last_Input</value>
         <variableId>ec11afff-ce73-4cf9-b5de-c26153924e84</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>1bfd46bb-abcd-44bd-bc46-7eed0f2e8b36</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Phone_Input</value>
         <variableId>ab4e7cba-fb95-4dfc-a978-68915daf65c0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>1bfd46bb-abcd-44bd-bc46-7eed0f2e8b36</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Email_Input</value>
         <variableId>8f398eeb-a81f-4d98-89be-8ee358b51eef</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>1bfd46bb-abcd-44bd-bc46-7eed0f2e8b36</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Address_Input</value>
         <variableId>29faef44-e5cb-4401-8f08-dd9104ceb397</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>1bfd46bb-abcd-44bd-bc46-7eed0f2e8b36</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>City_Input</value>
         <variableId>f43f257b-3cd1-459e-8fe5-a86d4db5615b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>1bfd46bb-abcd-44bd-bc46-7eed0f2e8b36</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>State_Input</value>
         <variableId>a28fc4fe-12b9-49fa-9f68-2c62d67fd4b4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>1bfd46bb-abcd-44bd-bc46-7eed0f2e8b36</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Zipcode_Input</value>
         <variableId>b1489dcb-a52f-401a-aa63-91b4b63f33da</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>1bfd46bb-abcd-44bd-bc46-7eed0f2e8b36</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Country_Input</value>
         <variableId>99789890-40ac-48c7-ba94-432d99ed1649</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
